### ISSUE TITLE
Passing multiple options via --build-options

### ISSUE THREAD

**Issue by thomasmarsh** [bazelbuild/xcode#10]
Tulsi provides a command line option to pass additional build options on the command line. It is unclear if it is possible or how to pass multiple options. For example, we would like to pass both "--noexperimental_enable_objc_cc_deps" and "--define=xyz". It appears that the buildOptions are stored internally in as a string. Passing `--build-options "--noexperimental_enable_objc_cc_deps --define=xyz"`, for example, does not work.

**Comment by thomasmarsh** [comment]
Correction: I have this working now. Passing a space-separated list of strings works. I simply had an error in my script which was performing this logic. We can close this issue, but I might suggest that the documentation clarify that this is a space separated list analogous to how the values are specified in the UI.

@kelvinchan-google

**Comment by kelvinchan-google** [comment]
Great to hear that it's working with a few tweaks. I agree that this isn't documented very well so I'll see if I can update the documentation to make this a bit more explicit.

I'll go ahead and close this issue as you've suggested.
